[tool.poetry]
name = "lab14-2021-base"
version = "0.1.0"
description = ""
authors = ["Roman Bartusiak <roman@stashaway.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"
ariadne = "^0.14.0"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
